import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const nodeBuiltins = [...builtinModules, ...builtinModules.map((m) => `node:${m}`)];

const jsContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...nodeBuiltins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

const cssContext = await esbuild.context({
	entryPoints: ["src/styles/index.css"],
	bundle: true,
	outfile: "styles.css",
	logLevel: "info",
	minify: prod,
});

if (prod) {
	await Promise.all([jsContext.rebuild(), cssContext.rebuild()]);
	process.exit(0);
} else {
	await Promise.all([jsContext.watch(), cssContext.watch()]);
}
